SELECT * FROM ORDER_INFO;
SELECT ORDER_ID
			,SHIPPING_ORDER_NO
			,CARGO_NAME
			,SHIPPING_DATE
			,SENDER_NAME
			,FROM_LOCATION
			,TO_LOCATION
			,ORDER_STATUS
			,ORDER_RECEPT_TIME
			,SENDER_PHONE
			,RECEIVER_PHONE
			,RECEIVER_NAME 
		FROM ORDER_INFO WHERE ORDER_ID='orderId';
		
		SELECT 	R.ORDER_ID,R.UPDATE_MSG,R.UPDATE_STATUS,R.UPDATE_TIME 
		FROM 	SHIPPING_RECORDS R 
		LEFT 	JOIN USER_ORDER_MAPPING M ON R.ORDER_ID = M.ORDER_ID
		WHERE 	M.USER_ID = 'userId'
		ORDER BY R.UPDATE_TIME;
		
		SELECT ORDER_ID
			,SHIPPING_ORDER_NO
			,CARGO_NAME
			,SHIPPING_DATE
			,SENDER_NAME
			,FROM_LOCATION
			,TO_LOCATION
			,ORDER_STATUS
			,ORDER_RECEPT_TIME
			,SENDER_PHONE
			,RECEIVER_PHONE
			,RECEIVER_NAME 
		FROM ORDER_INFO WHERE ORDER_ID='orderId2'